// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:13d47946-b4fa-4f50-9e23-a962a8a6d860',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'phototagger-hosting-mobilehub-1939271982',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd1z9ypjk7jnq48.cloudfront.net',
aws_mobile_analytics_app_id : '25c3cfa1b03e4893b673b8bb68e4528c',
aws_project_id : '72f051e4-2f17-486f-a9e1-8b58d6c16da2',
aws_project_name : 'phototagger',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'phototagger-mobilehub-1939271982',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});